#mybatis:
#  type-aliases-package: com.uhasoft.dac.entity
##  mapper-locations: classpath:mapper/*.xml
#
#mapper:
#  mappers:
#    - tk.mybatis.springboot.util.MyMapper
#  not-empty: false
#  identity: MYSQL
#
#pagehelper:
#  helperDialect: mysql
#  reasonable: true
#  supportMethodsArguments: true
#  params: count=countSql
spring:
  datasource:
#    schema: import.sql
    url: jdbc:mysql://localhost:3306/dac?autoReconnect=true&useUnicode=true&characterEncoding=utf-8
    username: root
    password: letmein
#    driverClassName: com.mysql.jdbc.Driver
logging:
  level:
    root: INFO
    com:
      uhasoft:
        dac:
          dao: TRACE